### ISSUE TITLE
Changing modes causes brief token recolor

### ISSUE THREAD

**Issue by radu781** [kensleDev/vscode-nvim-ui#14]
Changing between any mode (normal-insert, normal-visual, normal-visual line, normal-replace, insert-normal etc) causes some tokens to be colored differently for a split second and then get the intended color again. This is not specific to the used theme (tested on default dark+)
Removing this code in the `.lua` config fixes this issue (but basically disables the extension)
```lua
vim.api.nvim_exec([[
    " THEME CHANGER
    function! SetCursorLineNrColorInsert(mode)
        " Insert mode: blue
        if a:mode == "i"
            call VSCodeNotify('nvim-theme.insert')

        " Replace mode: red
        elseif a:mode == "r"
            call VSCodeNotify('nvim-theme.replace')
        endif
    endfunction

    augroup CursorLineNrColorSwap
        autocmd!
        autocmd ModeChanged *:[vV\x16]* call VSCodeNotify('nvim-theme.visual')
        autocmd ModeChanged *:[R]* call VSCodeNotify('nvim-theme.replace')
        autocmd InsertEnter * call SetCursorLineNrColorInsert(v:insertmode)
        autocmd InsertLeave * call VSCodeNotify('nvim-theme.normal')
        autocmd CursorHold * call VSCodeNotify('nvim-theme.normal')
    augroup END
]], false)
```
See attached videos for actual vs expected behaviours

https://github.com/kensleDev/vscode-nvim-ui/assets/75218616/7ea59cb5-a88c-4517-9ea5-c6b53b64bbed

https://github.com/kensleDev/vscode-nvim-ui/assets/75218616/11cc8a73-9486-499d-8131-773187ccbfa2

settings.json
```json
    "nvim-ui.nvimColorCustomizationKeys": [
        "tab.activeBorder",
        "editorCursor.foreground",
        "statusBarItem.remoteBackground"
    ],
    "workbench.colorCustomizations": {
        "tab.activeBorder": "#267bd2",
        "editorCursor.foreground": "#267bd2",
        "statusBarItem.remoteBackground": "#267bd2"
    },
```
Versions:
- neovim ui modifier: 0.1.5
- vscode neovim: 1.1.3
- vscodium: 1.84.2

**Comment by kensleDev** [comment]
Thanks for reporting this and sorry for the delay in picking this up. 

I didn't come across this in my latest testing and I'm not using the plugin in my workflow any more (gone full neovim) so havn't used the latest version extensivly. It seems latest changes to fix the delay when exiting visual mode may have introduced this. 

In the meantime removing this line in the config: 

```
autocmd ModeChanged [vV\x16]*:* call VSCodeNotify('nvim-theme.normal')
```

should revert the behavoir as it was in the last release (when exiting visual mode it can take 1-5 seconds for the colors to update). I will investigate to see if I can figure out what's going on here.

**Comment by radu781** [comment]
I tried the mentioned fix but I wasn't able to get it to work, also waiting for the update to occur is not what I want, I was looking for a more instant update.

In the meantime I found a solution using the [Apc Customize UI++](https://open-vsx.org/extension/drcika/apc-extension) extension that colors the mode indicator and host status icon. It also allows for more fine grained control over the modes.
I used the following config:

`fonts.css`
```css
:root {
  --asvetliakov-insert: #859900;
  --asvetliakov-visual: #fc4444;
  --asvetliakov-visual-block: #e57575;
  --asvetliakov-visual-line: #a50808;
  --asvetliakov-replace: #964ff2;
}

[aria-label^="-- INSERT --"] {
  background-color: var(--asvetliakov-insert) !important;
}

[aria-label^="-- VISUAL --"] {
  background-color: var(--asvetliakov-visual) !important;
}

[aria-label^="-- VISUAL LINE --"] {
  background-color: var(--asvetliakov-visual-line) !important;
}

[aria-label^="-- VISUAL BLOCK --"] {
  background-color: var(--asvetliakov-visual-block) !important;
}

[aria-label^="-- REPLACE --"] {
  background-color: var(--asvetliakov-replace) !important;
}
```

`fonts.js`
```js
const status_host = document.querySelector(
  ".monaco-workbench .part.statusbar>.items-container>.statusbar-item.remote-kind"
);

const map = [
  {
    selector: '[aria-label^="-- INSERT --"]',
    property: "--asvetliakov-insert",
  },
  {
    selector: '[aria-label^="-- VISUAL --"]',
    property: "--asvetliakov-visual",
  },
  {
    selector: '[aria-label^="-- VISUAL BLOCK --"]',
    property: "--asvetliakov-visual-block",
  },
  {
    selector: '[aria-label^="-- VISUAL LINE --"]',
    property: "--asvetliakov-visual-line",
  },
  {
    selector: '[aria-label^="-- REPLACE --"]',
    property: "--asvetliakov-replace",
  },
];

function domMutations(mutations) {
  mutations.forEach((mutation) => {
    if (mutation.type == "childList" && mutation.addedNodes.length > 0) {
      let changed = false;
      map.forEach(({ selector, property }) => {
        const element = document.querySelector(selector);
        if (element) {
          const color = getComputedStyle(document.documentElement).getPropertyValue(property);
          status_host.style.backgroundColor = color;
          changed = true;
        }
      });
      if (!changed) {
        status_host.style.backgroundColor = "var(--vscode-statusBarItem-remoteBackground)";
      }
    }
  });
}

const observer = new MutationObserver(domMutations);
const targetNode = document.body;
const config = { childList: true, subtree: true };
observer.observe(targetNode, config);
```
`settings.json`
```json
"apc.imports": [
    "file:///path/tofonts.css",
    "file:///path/to/fonts.js",
],
```

This is the outcome and is exactly how I wanted to use this extension:

https://github.com/kensleDev/vscode-nvim-ui/assets/75218616/0d68ef9c-9df4-4424-9215-9c0aa486e32b

Feel free to close this issue if you are taking a break from this project, the solution I provided should work fine for most users.

**Comment by kensleDev** [comment]
@radu781 - Thanks for the update. The plugin you have linked looks really good and super fast!

I did dig into this and spent a fair bit of time when you raised this trying to get it working unsucessfully. I've been very busy over the holiday period so it hasn't gotten full the attention it deserves. 

I'm currently using Neovim directly without VSCode so I'm not using the plugin in my workflow anymore. With that in mind I may deprecite this plugin as it looks like the alternative you have found is better fit for purpose. Looks like they manipulating the Electron window where I'm just shoving some lines in settings.json. It's always been a hacky solution and not using VSCode as my daily driver has meant it keeps slipping off my radar. 

Thanks again for bringing [Apc Customize UI++](https://open-vsx.org/extension/drcika/apc-extension) to my attention. I will leave this open until I've made my decsion about depricating / done a bit more research but the more I think about it, more than likley I will redirect users to the solution you have provided.

**Comment by radu781** [comment]
I double checked the css and js files and what I pasted above is identical. My unmodified `settings.json` looks like this:
```json
    "apc.imports": [
        "file:///C:/Users/Radu/source/repos/config/vscode/fonts.css",
        "file:///C:/Users/Radu/source/repos/config/vscode/fonts.js",
    ],
```
Are you sure the js and css files are loaded properly? Changes to these files are not done live are require an app restart. Try adding this and reload the window from the command center or restart the app. If the whole app is red it means that the files are properly loaded
```css
.monaco-workbench {
	background-color: red !important;
}
.monaco-split-view2.vertical>.monaco-scrollable-element>.split-view-container>.split-view-view {
	width: 0%
}
```
